name: "Feature request / Feature-Anfrage"
description: "Suggest an idea or enhancement for the WLANThermo Home Assistant integration. / Schlagen Sie eine Idee oder Verbesserung für die WLANThermo Home Assistant Integration vor."
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request / Feature-Anfrage
        Please describe your idea or enhancement below. / Bitte beschreiben Sie Ihre Idee oder Verbesserung unten.

  - type: input
    id: ha_version
    attributes:
      label: "Home Assistant version / Home Assistant Version"
      description: "What version of Home Assistant are you running? (e.g., 2024.1.0) / Welche Version von Home Assistant verwenden Sie? (z.B. 2024.1.0)"
      placeholder: "2024.1.0"
    validations:
      required: false

  - type: input
    id: component_version
    attributes:
      label: "WLANThermo integration version / WLANThermo Integrationsversion"
      description: "What version/commit of the integration are you using? (e.g., v1.2.3 or commit hash) / Welche Version/Commit der Integration verwenden Sie? (z.B. v1.2.3 oder Commit-Hash)"
      placeholder: "v1.2.3"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "Describe the feature / Beschreiben Sie das Feature"
      description: "A clear and concise description of the feature or enhancement you are requesting. / Eine klare und präzise Beschreibung des gewünschten Features oder der Verbesserung."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation and use case / Motivation und Anwendungsfall"
      description: "Why do you want this feature? How would you use it? / Warum möchten Sie dieses Feature? Wie würden Sie es nutzen?"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional context / Weitere Informationen"
      description: "Add any other context or screenshots about the feature request here. / Fügen Sie hier weitere Informationen oder Screenshots zur Feature-Anfrage hinzu."
    validations:
      required: false
